# =============================================================================
#  GenoSim R package ??? data.R
#  Example data accessors and documentation
# =============================================================================

#' Example Pedigree: FAM_KHAN (25-member, 4-generation consanguineous family)
#'
#' @description
#' A 25-member four-generation pedigree representing a consanguineous clinical
#' genetics family (FAM_KHAN). Contains four affected individuals with elevated
#' inbreeding coefficients, suitable for testing pedigree-constrained
#' simulation workflows.
#'
#' @format A \code{data.frame} with 25 rows and 7 columns:
#' \describe{
#'   \item{\code{individual_id}}{Unique individual identifier (character).}
#'   \item{\code{father_id}}{Father's ID or \code{"0"} for founders.}
#'   \item{\code{mother_id}}{Mother's ID or \code{"0"} for founders.}
#'   \item{\code{sex}}{Integer: 1 = male, 2 = female.}
#'   \item{\code{phenotype}}{Integer: 1 = unaffected, 2 = affected.}
#'   \item{\code{family_id}}{Family label (\code{"FAM_KHAN"}).}
#'   \item{\code{generation}}{Integer generation depth (0 = founders).}
#' }
#'
#' @details
#' The pedigree contains:
#' \itemize{
#'   \item Generation 0: 4 founders (2 couples)
#'   \item Generation 1: 6 offspring
#'   \item Generation 2: 9 offspring, including one consanguineous mating
#'     (parents are first-degree relatives) and one affected individual
#'   \item Generation 3: 6 offspring, three affected
#' }
#' Inbreeding coefficients (\eqn{F}) range from 0 (founders) to 0.375 for
#' offspring of related parents in generation 2.
#'
#' @usage data(example_pedigree)
#'
#' @source Synthetic data generated by \code{generate_test_data()} bundled
#'   within the GenoSim package.
#'
#' @examples
#' data(example_pedigree)
#' head(example_pedigree)
#' table(example_pedigree$phenotype)
#'
#' @seealso \code{\link{example_vcf_dir}}, \code{\link{read_pedigree}}
"example_pedigree"

#' Get Path to Example VCF Directory
#'
#' @description
#' Returns the path to the bundled example VCF directory containing 25
#' per-individual VCF files for the FAM_KHAN family (200 SNPs on chromosomes
#' 1???5 per individual, GRCh38 coordinates).
#'
#' @return Character scalar. Path to the directory containing example
#'   \code{.vcf} files.
#'
#' @details
#' The directory contains one VCF file per individual (e.g. \code{F001.vcf},
#' \code{I205.vcf}). File names correspond to \code{individual_id} values in
#' \code{\link{example_pedigree}}. Each VCF is standard VCFv4.2 with
#' \code{GT} format, PASS filter, and GRCh38 positions.
#'
#' These files can be passed directly to \code{\link{read_vcf_cohort}}.
#'
#' @examples
#' vcf_dir <- example_vcf_dir()
#' list.files(vcf_dir)
#'
#' \dontrun{
#' vcf <- read_vcf_cohort(vcf_dir)
#' }
#'
#' @seealso \code{\link{example_pedigree}}, \code{\link{read_vcf_cohort}}
#' @export
example_vcf_dir <- function() {
  system.file("extdata", "family_vcfs", package = "GenoSim")
}

#' Get Path to Example Pedigree CSV File
#'
#' @description
#' Returns the path to the bundled example pedigree CSV file for the FAM_KHAN
#' family.
#'
#' @return Character scalar. Full path to \code{family_pedigree.csv}.
#'
#' @examples
#' ped_path <- example_ped_path()
#' \dontrun{
#' ped <- read_pedigree(ped_path)
#' }
#'
#' @seealso \code{\link{example_vcf_dir}}, \code{\link{read_pedigree}}
#' @export
example_ped_path <- function() {
  system.file("extdata", "family_pedigree.csv", package = "GenoSim")
}
